# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: thinkific 0.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "thinkific"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["v p"]
  s.date = "2018-05-22"
  s.description = "Thinkific is an online education / course management system. It has a public API. This gem wraps the API and gives you equivalent ruby objects to work with."
  s.email = "piousbox@vs-MacBook-Pro.local"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/thinkific.rb",
    "lib/thinkific/course.rb",
    "lib/thinkific/user.rb",
    "test/helper.rb",
    "test/test_thinkific.rb",
    "thinkific.gemspec"
  ]
  s.homepage = "http://github.com/piousbox/thinkific"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Thin ruby wrapper around Thinkific ReSTful API. Gives you ruby objects for those https requests."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.3.9"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 2.3.9"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 2.3.9"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

